- alias: tristal arrival
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_boolean.tristal_away_mode
    to: false
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.tristal_away_mode
    - service: lock.unlock
      entity_id: lock.back_door
    - service: script.master_bedroom_on
